trigger:
  branches:
    include:
      - main # Rama que activará la pipeline.

pool:
  vmImage: 'ubuntu-latest' # Máquina virtual de ejecución.

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x' # Especifica la versión de Node.js (ajusta según tu proyecto).
    displayName: 'Usar Node.js 16'

  - script: npm install
    displayName: 'Instalar dependencias'

  - script: npm run build
    displayName: 'Construir la aplicación'

  - script: npm test
    displayName: 'Ejecutar pruebas'